spring:
  application:
    name: distributed-discovery
server:
  port: 53000
eureka:
  server:
    enable-self-preservation: false # 关闭服务器自我保护。客户端心跳检测 15 分钟内错误达到 80% 服务器会保护，导致别人认为还是好用的服务。
    eviction-interval-timer-in-ms: 10000 # 清理间隔（单位毫秒，默认是 60 * 1000）。5 秒将客户端剔除的服务在服务注册列表中剔除。
    shouldUseReadOnlyResponseCache: true # Eureka 是 CAP 理论中基于 AP 策略，为了保证强一致性关闭此切换 CA。默认不关闭。false 关闭。
  client:
    register-with-eureka: false # 不作为一个客户端注册到注册中心。
    fetch-registry: false # 为 true 时可以启动，但报异常：can't execute request on any known server。
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:53000/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
